server:
  port: 8443

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: order_consumer_group
      properties:
        spring.json.trusted.packages: 'org.pal.models'
    bootstrap-servers: 127.0.0.1:9092