server:
  port: 8443

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: order_consumer_group
      properties:
        spring.json.trusted.packages: 'org.pal.models'
    bootstrap-servers: 127.0.0.1:9092

  datasource:
    url: jdbc:mysql://localhost:3306/spring_kafka_db  # Replace with your database URL
    username: root                      # Replace with your database username
    password: root                      # Replace with your database password
    driver-class-name: com.mysql.cj.jdbc.Driver           # Replace with your database driver class name
